accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_view

from .views import (
    CreateUserView,
    profile_page,
    user_update,
    change_password,
    UserDetailView,
)  # UserProfileView # CreateDoneView

app_name = "accounts"

urlpatterns = [
    path("create/", CreateUserView.as_view(), name="create_account"),
    path("detail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("update/", user_update, name="update_account"),
    # path('profile/', UserProfileView.as_view(), name='user_profile'),
    path("profile/", profile_page, name="user_profile"),
    path("change-password/", change_password, name="change_password"),
    # generic views
    # path('', include('django.contrib.auth.urls')),
    path("login/", auth_view.LoginView.as_view(), name="login"),
    path(
        "logout/",
        auth_view.LogoutView.as_view(),
        name="logout",
        kwargs={"next_page": "/"},
    ),
]

books/urls.py
from django.urls import path
from django.views import generic
from .views import (
    BookListView,
    BookDetailView,
    BookUpdateView,
    delete_book,
    user_booklist,
    user_booklist_update,
    BookCreateView,
    ReviewCreateView,
    review_update_view,
)

app_name = "books"

urlpatterns = [
    path("", BookListView.as_view(), name="books"),
    path("create/", BookCreateView.as_view(), name="create"),
    path("review-create/", ReviewCreateView.as_view(), name="review_create"),
    path("<slug>/review-update/", review_update_view, name="review_update"),
    path(
        "recommendations/",
        generic.TemplateView.as_view(template_name="books/recommendation.html"),
        name="recommendation",
    ),
    path("<slug>/detail/", BookDetailView.as_view(), name="detail"),
    path("<slug>/update/", BookUpdateView.as_view(), name="update"),
    path("<slug>/delete/", delete_book, name="delete"),
    path("user-booklist/", user_booklist, name="user_booklist"),
    path("user/booklist/update/", user_booklist_update, name="user_booklist_update"),
]

djBooks/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_view

# from django.conf.urls import include # 2 new line
from rest_framework.authtoken.views import obtain_auth_token  # 11

from accounts.forms import EmailValidationOnForgotPassword

urlpatterns = [
    path("", include("pages.urls", namespace="pages")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("searchs/", include("searchs.urls", namespace="searchs")),
    # path('api/books/', include('books.api.urls', namespace="api-books")),
    # path('admin/', admin.site.urls),
    # path('api/', include('books.api.urls')), # 3 new line
    path("auth/", obtain_auth_token),  # 11
    # path('', TemplateView.as_view(template_name='react.html')),
    # path('walking', TemplateView.as_view(template_name='walking.html')),
    # re_path(r'^books/', TemplateView.as_view(template_name='react.html')),
    # path('api/books/', include('books.api.urls', namespace='api-books')),
    path("books/", include("books.urls", namespace="books")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
    path("admin/", admin.site.urls),
    # generic views
    # path('', include('django.contrib.auth.urls')),
    path(
        "password-reset/",
        auth_view.PasswordResetView.as_view(
            form_class=EmailValidationOnForgotPassword,
            template_name="registration/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_view.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_view.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_view.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser, AbstractUser)


class UserManager(BaseUserManager):
    def create_user(self, email, password=None,**extra_fields):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(email=self.normalize_email(email),**extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        user = self.create_user(email,password=password,**extra_fields)
        user.is_admin = True
        user.save(using=self._db)
        return user

    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(email__icontains=query) | 
                         Q(name__icontains=query)| 
                         Q(location__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address',max_length=255,unique=True,)
    name = models.CharField(max_length=100, blank=True, null=True)
    # last_name = models.CharField(max_length=100,null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    image = models.ImageField(upload_to='user_profile_pic/%Y/%m/%d', default='default_profile_pic.png')

    objects = UserManager()

    USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    @property
    def get_full_name(self):
        full_name = self.email
        if self.name:
            full_name = self.name
        return full_name

    @property
    def get_absolute_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.id})
    
    # @property
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return self.is_admin

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return self.is_admin

    # @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

books/models.py
from django.db import models
from django.contrib.auth.views import get_user_model
from django.db.models.signals import pre_save
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from autoslug import AutoSlugField
from django.utils.text import slugify
from django.db.models import Q
# rating
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating

# from django.core.validators import validate_slug

# from .utils import unique_slug_generator

User = get_user_model()

Art = "Art"
Biography = "Biography" 
Business = "Business" 
Children = "Children's" 
Christian = "Christian" 
Classics = "Classics" 
Comics = "Comics" 
Cookbooks = "Cookbooks" 
Ebooks = "Ebooks" 
Fantasy = "Fantasy" 
Fiction = "Fiction" 
Graphic_Novels = "Graphic Novels" 
Historical_Fiction = "Historical Fiction" 
History = "History" 
Horror = "Horror" 
Memoir = "Memoir" 
Music = "Music" 
Mystery = "Mystery" 
Nonfiction = "Nonfiction" 
Poetry = "Poetry" 
Psychology = "Psychology" 
Romance = "Romance" 
Science = "Science" 
Science_Fiction = "Science Fiction" 
Self_Help = "Self Help" 
Sports = "Sports" 
Thriller = "Thriller" 
Travel = "Travel" 
Young_Adult = "Young Adult"


class Genres(models.Model):
    genres = models.CharField(max_length=120)

    def __str__(self):
        return "{0}".format(self.genres)


class BookManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(title__icontains=query) | 
                         Q(summary__icontains=query)| 
                         Q(slug__icontains=query)| 
                         Q(author__icontains=query)|
                        #  Q(genres__icontains=query)|
                         Q(timestamp__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs


class Book(models.Model):
    title = models.CharField(max_length=120)
    # slug = models.SlugField(blank=True)
    slug = AutoSlugField(populate_from='title', unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.CharField(max_length=120, blank=True, null=True)
    summary = models.TextField(blank=True, null=True)
    # genres = models.TextField(choices=GENRES, blank=True, null=True)
    genres = models.ManyToManyField(Genres, blank=True)
    cover_page = models.ImageField(upload_to='cover_pages/%Y/%m/%d', default='default_book_cover.png')
    timestamp = models.DateTimeField(auto_now_add=True)
    ratings = GenericRelation(Rating, related_query_name='books')

    # SLUG_REGEX = re.compile('^[-\w]+$')
    objects = BookManager()


    def __str__(self):
        return "{0}".format(self.title)

    def get_absolute_url(self):
        return reverse('books:detail', kwargs={'slug': self.slug})
    
    def is_owner(self, user):
        return self.user == user
    
    @property
    def avg_rating(self):
        avg = 0
        try:
            rating = Rating.objects.get(object_id=self.id)
            avg = rating.average
        except:
            pass
        return avg

    class Meta:
        ordering = ['-timestamp']

    # def save(self, *args, **kwargs):
    #     # value = str(self.title + self.id)
    #     # if self.slug == None:
    #     super().save(*args, **kwargs)
        
    #     value = "{obj_title}-{obj_id}".format(obj_title=self.title, obj_id=self.id)
    #     self.slug = slugify(value, allow_unicode=True)

# def pre_save_receiver(sender, instance, *args, **kwargs): 
#    if not instance.slug: 
#        instance.slug = unique_slug_generator(instance) 


# pre_save.connect(pre_save_receiver, sender = Book) 


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="book_review")
    review = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [['user', 'book']]


class BooklistManager(models.Manager):
    def new_or_get(self, request):
        # for key, value in self.request.session.items():
        #     print("\n", '{} => {}'.format(key, value), "\n")
        book_id = request.session.get("book_id", None)
        qs = self.get_queryset().filter(id=book_id)
        if qs.count() == 1:
            new_obj = False
            book_obj = qs.first()
            if request.user.is_authenticated and book_obj.user is None:
                book_obj.user = request.user
                book_obj.save()
        else:
            book_obj = Booklist.objects.new(user=request.user)
            new_obj = True
            # request.session['book_id'] = book_obj.id
        return book_obj, new_obj

    def new(self, user=None):
        # user_obj = None
        # if user is not None:
        if user.is_authenticated:
            user_obj = user
            if self.model.objects.filter(user=user_obj).count() > 0:
                return self.model.objects.get(user=user_obj)
            return self.model.objects.create(user=user_obj)
        return None


class Booklist(models.Model):
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    books = models.ManyToManyField(Book, blank=True)

    objects = BooklistManager()

    def get_absolute_url(self):
        return reverse('books:user_booklist')

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    PasswordChangeForm,
)
from django.views.generic import View, FormView

from django.http import JsonResponse
from django.core import serializers

from books.models import Book, Booklist

# from .mixins import UserCreateAjaxFormMixin
from .forms import UserUpdateForm, UserCreateForm
from .models import User


class CreateUserView(generic.FormView):
    # model = User
    # fields = ['email', 'password']
    form_class = UserCreateForm
    template_name = "accounts/user_form.html"
    success_url = "/accounts/profile/"

    def form_invalid(self, form):
        response = super(CreateUserView, self).form_invalid(form)
        return response

    def form_valid(self, form):
        response = super(CreateUserView, self).form_valid(form)

        user = form.save(commit=False)
        password = form.cleaned_data["password"]
        user.set_password(password)
        user.save()

        authenticate(
            email=form.cleaned_data["email"],
            password=form.cleaned_data["password"],
        )
        login(self.request, user)
        ser_user = serializers.serialize(
            "json",
            [
                user,
            ],
        )
        return response


# class CreateUserView(generic.CreateView):
#     model = User
#     fields = ['email', 'password']
#     success_url = '/accounts/profile/'

#     def form_valid(self, form):
#         super(CreateUserView, self).form_valid(form)
#         user = form.save()
#         authenticate(email=form.cleaned_data['email'], password=form.cleaned_data['password'],)
#         login(self.request, user)
#         return redirect('accounts:user_profile')


@login_required
def profile_page(request):
    # user = request.user
    user_books = Book.objects.filter(user=request.user)
    booklist_obj = Booklist.objects.new_or_get(request)
    return render(
        request,
        "accounts/user_profile.html",
        {"user_books": user_books, "booklist_obj": booklist_obj},
    )


class UserDetailView(generic.DetailView):
    model = User
    template_name = "accounts/user_detail.html"

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        try:
            book_list_obj = Booklist.objects.get(user=self.get_object())
        except:
            book_list_obj = Booklist.objects.new(user=self.get_object())
        context["detail_user_booklist"] = book_list_obj
        context["detail_user_books"] = Book.objects.filter(user=self.get_object())
        return context


@login_required
def user_update(request):
    if request.method == "POST":
        form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "Account updated!")
            return redirect("accounts:user_profile")
        else:
            messages.error(request, "Please correct the error(s) below. ")
    else:
        form = UserUpdateForm(instance=request.user)
    return render(
        request,
        "accounts/user_setting.html",
        {
            "form": form,
        },
    )


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Password changed!")
            return redirect("accounts:user_profile")
        else:
            messages.error(request, "Please correct the error(s) below. ")
    else:
        form = PasswordChangeForm(request.user)
    return render(
        request,
        "accounts/password_change.html",
        {
            "form": form,
        },
    )

templates/accounts/password_change.html
{% extends 'base.html' %}
{% block title %}Change Password | ACO{% endblock title %}
{% load static %}

{% block content %}

<br><br><br>
<div class="container">

<p class="display-4 text-center">Change Password </p>

{% if form.errors %}<div class="alert alert-danger">Please correct the error(s) below</div>{% endif %}

<div class="row text-dark">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="container"><br>
            
                <form action="" method="POST">{% csrf_token %}
                    <label>{{ form.old_password.label }}</label>
                    <!-- {{ form.old_password }}  -->
                    <input type="password" class="form-control" name="old_password" id="old_password" required>
                    <span class="text-danger">{{ form.old_password.errors }}</span>
                    <p class="text-muted-xs">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</p><hr>

                    <label>{{ form.new_password1.label }}</label>
                    <!-- {{ form.new_password1 }} -->
                    <input type="password" class="form-control" name="new_password1" id="new_password1" required>
                    <span class="text-danger">{{ form.new_password1.errors }}</span>
                    <p class="text-muted-xs">
                        Your password can't be too similar to your other personal information.<br>
                        Your password must contain at least 8 characters.<br>
                        Your password can't be a commonly used password.<br>
                        Your password can't be entirely numeric.
                    </p><hr>

                    <label>{{ form.new_password2.label }}</label>
                    <!-- {{ form.new_password2 }} -->
                    <input type="password" class="form-control" name="new_password2" id="new_password2" required>
                    <span class="text-danger">{{ form.new_password2.errors }}</span>
                    <p class="text-muted-xs">Enter the same password as before, for verification.</p>

                <center><input class="btn btn-lg btn-primary" type="submit" value="Change Password"></center><br>
                </form>
            </div>
        </div>
    </div>
</div>

</div>
<br><br><br>
</section>

{% endblock content %}

templates/accounts/user_form.html
{% extends 'base.html' %}
{% block title %}Registration - djBooks{% endblock title %}

{% block content %}

<div class="container">
    <div class="row py-5 my-5">
        <div class="col-md-8 border-right">
            <h1 class="display-4">Create Account</h1> <br>

            {% if messages %}
            {% for message in messages %}
            {% if message.tags == 'error' %}
            <div class="alert alert-danger">
                <i class="fas fa-exclamation-circle"></i> {{ message }}
            </div>
            {% else %}
            <div class="alert alert-success">
                <i class="fas fa-check-circle"></i> {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}

            <form id="account-create-form" action="{% url 'accounts:create_account' %}" method="POST">
                {% csrf_token %}
                <label for="id_email">Email address:</label>
                <input type="email" name="email" maxlength="255" class="form-control" required="" id="id_email">
                <span id="form-email-error"></span>
                <label for="id_password">Password:</label>
                <input type="password" name="password" maxlength="128" class="form-control" required=""
                    id="id_password">
                <br>
                <button id="form-submit-btn" class="btn btn-lg btn-success" type="submit">Create account</button>
            </form>
            <p class="text-muted">Already have an account ? <a href="{% url 'accounts:login' %}" class="link">Login
                    Here</a></p>

        </div>
        <div class="col-md-4">
            <ul class="lead">
                <li>Read books</li>
                <li>Get recommendations</li>
                <li>Group discussion</li>
                <li>Friends</li>
            </ul>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}

<!-- <script>
    var formData = document.getElementById('account-create-form');
    var submitBtn = document.getElementById('form-submit-btn');
    
    formData.addEventListener('submit', () => {
        submitBtn.innerHTML = "<span class='spinner-border spinner-border-sm' role='status' aria-hidden='true'></span> Loading...";
        submitBtn.setAttribute("disabled", "");

        // disable inputes
        // formData.childNodes[3].disabled = true;
        // formData.childNodes[9].disabled = true;

        window.setTimeout(function () {
            // when asyncronous action is done, remove the spinner
            // re-enable button/fieldset
            submitBtn.innerHTML = "Create Account"
            submitBtn.removeAttribute("disabled", "");
            formData.childNodes[3].disabled = false;
            formData.childNodes[9].disabled = false;
        }, 4000);
    }, false);
</script> -->

{% endblock js %}

templates/accounts/user_profile.html
{% extends 'base.html' %}
{% block title %}{{ request.user.get_full_name }} - djBooks{% endblock title %}

{% block content %}

{% if request.user.is_authenticated %}

<style>
  .delete-btn {font-size: 10px; padding: 3px 7px;border: 1px solid transparent;border-radius: 50%;color: transparent;}
  tr:hover .delete-btn {border-color: #afafaf; color: #000; background: #fff;}
  .delete-btn:hover {background: rgb(28, 104, 175) !important; color: #fff !important;}
  @media (max-width: 1000px) {
    .delete-btn {
      border: 1px solid #afafaf !important;
      color: #000 !important;
    }
  }
</style>

{% if messages %}
    {% for message in messages %}
        <div class="alert-auto-dismiss" id="alert-auto-dismiss-{{ forloop.counter }}">
            {{ message }}
            <button type="submit" class="auto-close" id="auto-close" onclick="autoDesmiss({{ forloop.counter }})">&times;</button>
        </div>
    {% endfor %}
{% endif %}

<div class="container">
    <h1 class="title-1 py-4 pl-3 text-light bg-gradient-sky"><br> Welcom {{ user.get_full_name }}</h1>
    <div class="row">
        <div class="col-md-3 p-2">
            <div class="card p-3">
                <img src="{{ user.image.url }}" alt="" class="mx-auto img-rounded" width="200px" style="max-width: 200px;">
                <p class="text-center lead"> {{ user.get_full_name }}</p>
                - Full Name {{ user.name }} <br>
                - Location/Address {{ user.location }}
                <div class="text-muted p-2 border mb-3">
                    <li>{{ user_books.count }} books </li>
                    <li>{{ book_list_obj.books.all.count }} books in <a href="#">booklist</a></li>
                </div>
                <div class="d-flex justify-content-between">
                    <a href="{% url 'accounts:change_password' %}" class="btn btn-sm btn-outline-secondary"> <span>&#128273; <small>Password</small></span></a>
                    <a href="{% url 'accounts:update_account' %}" class="btn btn-sm btn-outline-secondary"> <span>&#9881;</span> <small>Setting</small></a>
                </div>
            </div>
        </div>
        <div class="col-md-9 p-2">
            <div class="card p-3 mb-3">
                <p class="lead">Books by {{ user.get_full_name }} ({{ user_books.count }}) <a href="{% url 'books:create' %}" class="btn btn-primary" style="float: right">&#43; Add book</a></p>
                <table class="table table-responsive table-hover">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Book Title</th>
                        <th scope="col">Author</th>
                        <th scope="col">Uploaded Date</th>
                        <th scope="col"></th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for book in user_books %}

                      <tr class="text-muted">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></td>
                        <td>{{ book.author }}</td>
                        <td>{{ book.timestamp|timesince }} ago</td>
                        <td>
                          <a href="{% url 'books:update' slug=book.slug %}" title="Edit"><span class="delete-btn">&#9998;</span></a> 
                          <a href="{% url 'books:delete' slug=book.slug %}" title="Delete"><span class="delete-btn">&#10005;</span></a>
                        </td>
                      </tr>
                      {% empty %}
                      <tr>
                        <th scope="row"></th>
                        <td></td>
                        <td class="alert alert-warning"> You have no book, start by creating one. </td>
                        <td></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card p-3">
                <p class="lead">Booklist ({{ book_list_obj.books.all.count }})</p>
                <table class="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Book Title</th>
                        <th scope="col">Book by</th>
                        <th scope="col">Author</th>
                        <th scope="col"></th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for book in book_list_obj.books.all %}
                      <tr class="text-muted">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></td>
                        <td>{{ book.user }}</td>
                        <td>{{ book.author }}</td>
                        <td>
                          <!-- <form  id="booklist-form-id" class="booklist-form" action="{% url 'books:user_booklist_update' %}" method="POST" data-url="{% url 'books:user_booklist_update' %}">
                            <input type="hidden" name="book_id" id="id_book" value="{{ book.id }}" {% if  product.is_digital %}data-is-digital="true"{% endif%}/>
                            <button type="submit" class="btn">
                              <span class="delete-btn">&#10005;</span>
                            </button>
                          </form> -->
                          <form id="form-booklist-ajax" method="POST" action="{% url 'books:user_booklist_update' %}" data-endpoint="{% url 'books:user_booklist_update' %}"> {% csrf_token %}
                            <input type="hidden" name="book_id" id="book_id" value="{{ book.id }}"/>

                            <input type="hidden" name="next" id="next" value="{% url 'accounts:user_profile' %}"/>
                            <button type="submit" style="background: transparent; border: none;">
                              <span class="delete-btn">&#10005;</span>
                            </button>
                          </form>
                        </td>
                      </tr>
                      {% empty %}
                      <tr>
                        <th scope="row"></th>
                        <td></td>
                        <td class="alert alert-warning"> You have no book in your booklist, start by adding one. </td>
                        <td></td>
                      </tr>
                      {% endfor %}
                    </tbody> 
                </table><a href="{% url 'books:user_booklist' %}">Display more</a>
            </div>
        </div>
    </div>
</div>
<br><br><br><br>

{% endif %}

{% endblock %}

templates/accounts/user_setting.html
{% extends 'base.html' %}
{% block title %}Setting | ACO{% endblock title %}
{% load static %}

{% block content %}

<br><br><br>
<div class="container">
<p class="display-4 text-center">Account Settings <i class="fas fa-cogs text-orange"></i></p>

{% if form.errors %}<div class="alert alert-danger">Please correct the error(s) below</div>{% endif %}
<form class="text-dark" action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <div class="row mb-4 text-dark">
        <div class="col-md-6 mx-auto">
            <div class="card p-2">
                {{ form.email.label }}<br>{{ form.email }} <span class="text-danger">{{ form.email.errors }}</span><hr>
                {{ form.name.label }}<br>{{ form.name }} <span class="text-danger">{{ form.name.errors }}</span><hr>
                {{ form.location.label }}<br>{{ form.location }} <span class="text-danger">{{ form.location.errors }}</span><hr>
                {{ form.image.label }}<br>{{ form.image }} <span class="text-danger">{{ form.image.errors }}</span><hr>
            </div>
        </div>
    </div>

    <center>
        <button class="btn btn-primary" type="submit">Save</button>
    </center>
</form>
</div>
<br><br><br>

{% endblock content %}