books/urls.py
from django.urls import path
from django.views import generic
from .views import (
    BookListView,
    BookDetailView,
    BookUpdateView,
    delete_book,
    user_booklist,
    user_booklist_update,
    BookCreateView,
    ReviewCreateView,
    review_update_view,
)

app_name = "books"

urlpatterns = [
    path("", BookListView.as_view(), name="books"),
    path("create/", BookCreateView.as_view(), name="create"),
    path("review-create/", ReviewCreateView.as_view(), name="review_create"),
    path("<slug>/review-update/", review_update_view, name="review_update"),
    path(
        "recommendations/",
        generic.TemplateView.as_view(template_name="books/recommendation.html"),
        name="recommendation",
    ),
    path("<slug>/detail/", BookDetailView.as_view(), name="detail"),
    path("<slug>/update/", BookUpdateView.as_view(), name="update"),
    path("<slug>/delete/", delete_book, name="delete"),
    path("user-booklist/", user_booklist, name="user_booklist"),
    path("user/booklist/update/", user_booklist_update, name="user_booklist_update"),
]

djBooks/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_view

# from django.conf.urls import include # 2 new line
from rest_framework.authtoken.views import obtain_auth_token  # 11

from accounts.forms import EmailValidationOnForgotPassword

urlpatterns = [
    path("", include("pages.urls", namespace="pages")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("searchs/", include("searchs.urls", namespace="searchs")),
    # path('api/books/', include('books.api.urls', namespace="api-books")),
    # path('admin/', admin.site.urls),
    # path('api/', include('books.api.urls')), # 3 new line
    path("auth/", obtain_auth_token),  # 11
    # path('', TemplateView.as_view(template_name='react.html')),
    # path('walking', TemplateView.as_view(template_name='walking.html')),
    # re_path(r'^books/', TemplateView.as_view(template_name='react.html')),
    # path('api/books/', include('books.api.urls', namespace='api-books')),
    path("books/", include("books.urls", namespace="books")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
    path("admin/", admin.site.urls),
    # generic views
    # path('', include('django.contrib.auth.urls')),
    path(
        "password-reset/",
        auth_view.PasswordResetView.as_view(
            form_class=EmailValidationOnForgotPassword,
            template_name="registration/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_view.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_view.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_view.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.contrib.auth.views import get_user_model
from django.db.models.signals import pre_save
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from autoslug import AutoSlugField
from django.utils.text import slugify
from django.db.models import Q
# rating
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating

# from django.core.validators import validate_slug

# from .utils import unique_slug_generator

User = get_user_model()

Art = "Art"
Biography = "Biography" 
Business = "Business" 
Children = "Children's" 
Christian = "Christian" 
Classics = "Classics" 
Comics = "Comics" 
Cookbooks = "Cookbooks" 
Ebooks = "Ebooks" 
Fantasy = "Fantasy" 
Fiction = "Fiction" 
Graphic_Novels = "Graphic Novels" 
Historical_Fiction = "Historical Fiction" 
History = "History" 
Horror = "Horror" 
Memoir = "Memoir" 
Music = "Music" 
Mystery = "Mystery" 
Nonfiction = "Nonfiction" 
Poetry = "Poetry" 
Psychology = "Psychology" 
Romance = "Romance" 
Science = "Science" 
Science_Fiction = "Science Fiction" 
Self_Help = "Self Help" 
Sports = "Sports" 
Thriller = "Thriller" 
Travel = "Travel" 
Young_Adult = "Young Adult"


class Genres(models.Model):
    genres = models.CharField(max_length=120)

    def __str__(self):
        return "{0}".format(self.genres)


class BookManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(title__icontains=query) | 
                         Q(summary__icontains=query)| 
                         Q(slug__icontains=query)| 
                         Q(author__icontains=query)|
                        #  Q(genres__icontains=query)|
                         Q(timestamp__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs


class Book(models.Model):
    title = models.CharField(max_length=120)
    # slug = models.SlugField(blank=True)
    slug = AutoSlugField(populate_from='title', unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.CharField(max_length=120, blank=True, null=True)
    summary = models.TextField(blank=True, null=True)
    # genres = models.TextField(choices=GENRES, blank=True, null=True)
    genres = models.ManyToManyField(Genres, blank=True)
    cover_page = models.ImageField(upload_to='cover_pages/%Y/%m/%d', default='default_book_cover.png')
    timestamp = models.DateTimeField(auto_now_add=True)
    ratings = GenericRelation(Rating, related_query_name='books')

    # SLUG_REGEX = re.compile('^[-\w]+$')
    objects = BookManager()


    def __str__(self):
        return "{0}".format(self.title)

    def get_absolute_url(self):
        return reverse('books:detail', kwargs={'slug': self.slug})
    
    def is_owner(self, user):
        return self.user == user
    
    @property
    def avg_rating(self):
        avg = 0
        try:
            rating = Rating.objects.get(object_id=self.id)
            avg = rating.average
        except:
            pass
        return avg

    class Meta:
        ordering = ['-timestamp']

    # def save(self, *args, **kwargs):
    #     # value = str(self.title + self.id)
    #     # if self.slug == None:
    #     super().save(*args, **kwargs)
        
    #     value = "{obj_title}-{obj_id}".format(obj_title=self.title, obj_id=self.id)
    #     self.slug = slugify(value, allow_unicode=True)

# def pre_save_receiver(sender, instance, *args, **kwargs): 
#    if not instance.slug: 
#        instance.slug = unique_slug_generator(instance) 


# pre_save.connect(pre_save_receiver, sender = Book) 


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="book_review")
    review = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [['user', 'book']]


class BooklistManager(models.Manager):
    def new_or_get(self, request):
        # for key, value in self.request.session.items():
        #     print("\n", '{} => {}'.format(key, value), "\n")
        book_id = request.session.get("book_id", None)
        qs = self.get_queryset().filter(id=book_id)
        if qs.count() == 1:
            new_obj = False
            book_obj = qs.first()
            if request.user.is_authenticated and book_obj.user is None:
                book_obj.user = request.user
                book_obj.save()
        else:
            book_obj = Booklist.objects.new(user=request.user)
            new_obj = True
            # request.session['book_id'] = book_obj.id
        return book_obj, new_obj

    def new(self, user=None):
        # user_obj = None
        # if user is not None:
        if user.is_authenticated:
            user_obj = user
            if self.model.objects.filter(user=user_obj).count() > 0:
                return self.model.objects.get(user=user_obj)
            return self.model.objects.create(user=user_obj)
        return None


class Booklist(models.Model):
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    books = models.ManyToManyField(Book, blank=True)

    objects = BooklistManager()

    def get_absolute_url(self):
        return reverse('books:user_booklist')

templates/snippets/booklist_form.html
<form  id="booklist-form-id" class="booklist-form" action="{% url 'books:user_booklist_update' %}" method="POST" data-url="{% url 'books:user_booklist_update' %}">
    <input type="hidden" name="book_id" id="id_book" value="{{ obj.id }}" {% if  product.is_digital %}data-is-digital="true"{% endif%}/>
    {% if obj in book_list_obj.books.all %} <br>
        <button type="submit" id="booklist-submit-btn-{{ forloop.counter }}" onclick="toggleText(this.id)" class="btn btn-sm btn-outline-danger">
            Remove from my booklist
        </button>
    {% else %}
        <button type="submit" id="booklist-submit-btn-{{ forloop.counter }}" onclick="toggleText(this.id)" class="btn btn-sm btn-outline-success">
            Add to my booklist
        </button>
    {% endif %}
</form><br>

templates/snippets/recommendation.html
{% load ratings %}
<style>
    @media (max-width: 700px) {
        .row {
            display: block;
        }
    }
</style>

<div class="row">
    {% for obj in sorted_recomended_books %}
    <div class="col-md-6 p-3">
        <div class="book-card">
            <a href="{{ obj.get_absolute_url }}">
                <img src="{{ obj.cover_page.url }}" alt="" class="cover-page" />
            </a>
            <div class="summary py-3">
                <h6><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h6>
                <p class="pb-2 m-0">By:
                    <a href="{{ obj.user.get_absolute_url }}" class="text-muted">{{ obj.user.get_full_name }}</a> |
                    Author
                    <span class="text-muted">{{ obj.author }}</span>
                </p>
                <div class="d-flex text-muted">
                    <small>{% ratings obj %}</small>
                </div>
                {% include 'snippets/booklist_form.html' with obj=obj %}
                <p>{% if obj.summary %}<small>{{ obj.summary|truncatechars:80 }}</small>{% else %}<span
                        class="alert alert-warning p-2">No summary set for this book.</span>{% endif %}</p>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="alert alert-info w-100 text-center">Oops... This is soooo empty :(</div>
    {% endfor %}
</div>
<br><br><br>


<!-- <div class="d-block py-3" id="r-books">Loding recommendations...</div> -->


<!-- <script>
const recommandBooksEl = document.getElementById('r-books');


function loadRecommendations(booksElement){
    const xhr = new XMLHttpRequest();
    const method = 'GET';
    const url = '/api/books/recommendation/';
    const responseType = "json";

    xhr.responseType = responseType;
    xhr.open(method, url);

    function formatedItemEl(book){
        var formatedItem =  
            "<div class='col-6 d-flex align-items-center border p-0 m-3'>" + 
                "<a href='#'><img src=' " + book.cover_page + " ' alt='' width='100px' class='cover-page'></a>" +
                "<div class='card-summary mx-2'>" +
                    "<p><a href='#'><b>" + book.title + "{{ " + `${book.title}|safe` + " }} </b></a></p>" +
                    "<small>By: <a href='#' class='text-muted'>" + book.user + "</a>" + 
                        " | Author: <span class='text-muted'> " + book.author + "</span></small>" +
                    "<p>&#9733; &#9733; &#9733; &#9733; &#9733; <small class='text-muted'> 2,342 rating 5,343 review</small></p>" +
                    "<p>" + book.summary + "...</p>" +
                "</div>" +
            "</div>"
        return formatedItem;
    };

    xhr.onload = function() {
        const serverResponse = xhr.response;
        var final_list = "";
        for(var i=0; i<serverResponse.length; i++){
            final_list += "<div class='row'>" + formatedItemEl(serverResponse[i]) + "</div>";
        };
        booksElement.innerHTML = final_list;
    };
    
    xhr.send();
};
loadRecommendations(recommandBooksEl);

</script> -->

templates/snippets/review_form.html
{% if is_reviewed %}
<a href="{% url 'books:review_update' slug=obj.slug %}" class="btn btn-outline-primary">&#9998; Edit your review</a>
{% else %}
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#reviewForm" data-whatever="@getbootstrap">Write a review</button>
{% endif %}

<div class="modal fade" id="reviewForm" tabindex="-1" role="dialog" aria-labelledby="reviewFormLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="reviewFormLabel">New review</h5> 
        <button data-dismiss="modal" aria-label="Close">&times;</button>
      </div>
      <div class="modal-body">
        <form  id="review-form-id" class="review-form" action="{% url 'books:review_create' %}" method="POST" data-url="{% url 'books:review_create' %}">
            {% csrf_token %}
            <input type="hidden" name="next" id="id_next" value="{{ request.path }}" required/>
            <input type="hidden" name="user" id="id_user" value="{{ request.user.id }}" required/>
            <input type="hidden" name="book" id="id_book" value="{{ obj.id }}" required/>
            
            <label for="id_review">Write a review:</label>
            <textarea class="form-control" name="review" id="id_review" required></textarea><br>
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
      </div>
    </div>
  </div>
</div>