accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_view

from .views import (
    CreateUserView,
    profile_page,
    user_update,
    change_password,
    UserDetailView,
)  # UserProfileView # CreateDoneView

app_name = "accounts"

urlpatterns = [
    path("create/", CreateUserView.as_view(), name="create_account"),
    path("detail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("update/", user_update, name="update_account"),
    # path('profile/', UserProfileView.as_view(), name='user_profile'),
    path("profile/", profile_page, name="user_profile"),
    path("change-password/", change_password, name="change_password"),
    # generic views
    # path('', include('django.contrib.auth.urls')),
    path("login/", auth_view.LoginView.as_view(), name="login"),
    path(
        "logout/",
        auth_view.LogoutView.as_view(),
        name="logout",
        kwargs={"next_page": "/"},
    ),
]

books/urls.py
from django.urls import path
from django.views import generic
from .views import (
    BookListView,
    BookDetailView,
    BookUpdateView,
    delete_book,
    user_booklist,
    user_booklist_update,
    BookCreateView,
    ReviewCreateView,
    review_update_view,
)

app_name = "books"

urlpatterns = [
    path("", BookListView.as_view(), name="books"),
    path("create/", BookCreateView.as_view(), name="create"),
    path("review-create/", ReviewCreateView.as_view(), name="review_create"),
    path("<slug>/review-update/", review_update_view, name="review_update"),
    path(
        "recommendations/",
        generic.TemplateView.as_view(template_name="books/recommendation.html"),
        name="recommendation",
    ),
    path("<slug>/detail/", BookDetailView.as_view(), name="detail"),
    path("<slug>/update/", BookUpdateView.as_view(), name="update"),
    path("<slug>/delete/", delete_book, name="delete"),
    path("user-booklist/", user_booklist, name="user_booklist"),
    path("user/booklist/update/", user_booklist_update, name="user_booklist_update"),
]

djBooks/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_view

# from django.conf.urls import include # 2 new line
from rest_framework.authtoken.views import obtain_auth_token  # 11

from accounts.forms import EmailValidationOnForgotPassword

urlpatterns = [
    path("", include("pages.urls", namespace="pages")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("searchs/", include("searchs.urls", namespace="searchs")),
    # path('api/books/', include('books.api.urls', namespace="api-books")),
    # path('admin/', admin.site.urls),
    # path('api/', include('books.api.urls')), # 3 new line
    path("auth/", obtain_auth_token),  # 11
    # path('', TemplateView.as_view(template_name='react.html')),
    # path('walking', TemplateView.as_view(template_name='walking.html')),
    # re_path(r'^books/', TemplateView.as_view(template_name='react.html')),
    # path('api/books/', include('books.api.urls', namespace='api-books')),
    path("books/", include("books.urls", namespace="books")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
    path("admin/", admin.site.urls),
    # generic views
    # path('', include('django.contrib.auth.urls')),
    path(
        "password-reset/",
        auth_view.PasswordResetView.as_view(
            form_class=EmailValidationOnForgotPassword,
            template_name="registration/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_view.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_view.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_view.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import ContactCreateView, NewsAndEventList
from django.views import generic

app_name = 'pages'

urlpatterns = [
    # path('', home_view, name='home'),
    path('', generic.TemplateView.as_view(template_name='pages/index.html'), name='home'),
    path('about/', generic.TemplateView.as_view(template_name='pages/about.html'), name='about'),
    path('contact/', ContactCreateView.as_view(), name='contact'),
    path('news-and-events/', NewsAndEventList.as_view(), name='news_events'),
]

searchs/urls.py
from django.urls import path

from .views import SearchView

app_name = "searchs"

urlpatterns = [
    path("", SearchView.as_view(), name="query"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}  Books - READ WITH US {% endblock title %}</title>

    {% load static %}

    <meta content="APPUS, READ WITH US" name="keywords">
    <meta name="description" content="
    {% block description %}This is a Platform that allows you to connect with other like
    minded readers, swap books, discuss, comment and review books.{% endblock description %}">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/favicon.png' %}" rel="apple-touch-icon">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- star rating config -->
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v8.0" nonce="gM6KN4kX"></script>
    
    {% include 'navbar.html' %}

    {% block content %}
    {% endblock content %}
    
    {% include 'footer.html' %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

    <script>
        function autoDesmiss (counter) {
            document.getElementById(`alert-auto-dismiss-${counter}`).style.display = "none"
        }
    </script>

    <script>
        // using jQuery CSRF
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        // get the form
        $(document).ready(function(){
            var $myForm = $('.my-ajax-form')
            $myForm.addClass('added-class')
            $myForm.submit(function(event){
                event.preventDefault()
                var $formData = $(this).serialize()
                var $thisURL = $myForm.attr('data-url') || window.location.href // or set your own url
                $.ajax({
                    method: "POST",
                    url: $thisURL,
                    data: $formData,
                    success: handleFormSuccess,
                    error: handleFormError,
                })
            })
        
            var formEmailError = document.getElementById('form-email-error')
            function handleFormSuccess(data, textStatus, jqXHR){
                formEmailError.innerHTML = `<div class="alert-auto-dismiss bg-success" id="alert-auto-dismiss-{{ forloop.counter }}">
                    Account created. redirecting to your profile page...</div>`
                window.location.href = '/accounts/profile/'
                console.log(data)
                console.log(textStatus)
                console.log(jqXHR)
                $myForm[0].reset(); // reset form data
            }
        
            function handleFormError(jqXHR, textStatus, errorThrown){
                console.log(jqXHR)
                if(jqXHR.status === 400) {
                    formEmailError.innerHTML = `<p class='text-danger'>${jqXHR.responseJSON['email']}</p>`
                }
                console.log(jqXHR)
                console.log(textStatus)
                console.log(errorThrown)
            }
        })
        

        // get the form booklist
        $(document).ready(function(){
            var $myForm = $('.booklist-form')
            $myForm.addClass('added-class')
            $myForm.submit(function(event){
                event.preventDefault()
                var $formData = $(this).serialize()
                var $thisURL = $myForm.attr('data-url') || window.location.href // or set your own url
                $.ajax({
                    method: "POST",
                    url: $thisURL,
                    data: $formData,
                    success: handleFormSuccess,
                    error: handleFormError,
                })
            })
        
            function handleFormSuccess(data, textStatus, jqXHR){
                // window.location.href = '/accounts/profile/'
                // console.log(data)
                console.log(textStatus)
                console.log(jqXHR)
                $myForm[0].reset(); // reset form data
            }
        
            function handleFormError(jqXHR, textStatus, errorThrown){
                // console.log(jqXHR)
                // console.log(jqXHR)
                console.log(textStatus)
                console.log(errorThrown)
            }
        })
    </script>

    <script>
        function toggleText(button_id) {
            console.log(button_id)
            const submitBooklistBtn = document.getElementById(button_id);

            if(submitBooklistBtn.innerText === "Remove from my booklist"){
                submitBooklistBtn.innerHTML = "Add to my booklist";
                submitBooklistBtn.setAttribute('class', "btn btn-sm btn-outline-success");
            }
            else if(submitBooklistBtn.innerText === "Add to my booklist"){
                submitBooklistBtn.innerHTML = "Remove from my booklist";
                submitBooklistBtn.setAttribute('class', "btn btn-sm btn-outline-danger");
            }
        }
    </script>
    {% block js %}
    {% endblock js %}
</body>
</html>

templates/navbar.html
{% load static %}

<style>
  #navbar {background: #ffffffb3; transition: .5s;}
  .nav-link {
      padding-top: 10px;
      padding-bottom: 10px;
      border-bottom: 3px solid transparent;
  }
  .shadow-bottom {
      box-shadow: 0 10px 10px 0px #e2e2e2;
  }
  .nav-link:hover, .active {
      color: #38a3d4 !important;
      border-bottom-color: #38a3d4;
      transition: .2s;
  }
  .header-s-btn {
      border-top-right-radius: 2em;
      border-bottom-right-radius: 2em;
      border: 1px solid #ddd;
      background: #fff;
      color: gray;
      margin-left: -5px;
  }
  #navbar-brand-wrapper {
    position: absolute;
    display: block;
    top: 0;
    left: 0;
    padding: 20px;
    color: #fff !important;
    background: rgb(162, 5, 253);
    text-align: center;
    border-radius: 0 40px 5px;
    transition: .5s;
  }
  @media (max-width: 1000px) {
    #navbar {background: #fff !important;}
    #navbar-brand-wrapper small {
      display: none !important;
    }
  }
</style>

<nav id="navbar" class="navbar navbar-expand-xl navbar-light py-0 fixed-top">
    <div class="mr-5">F</div>
    <a class="navbar-brand" id="navbar-brand-wrapper" href="/">APPUS <br> <small style="font-size: 12px;">READ WITH US</small></a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse pl-5" id="navbarsExampleDefault">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item">
          <a class="nav-link active" href="/">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Book</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'books:books' %}">All Books</a>
            <a class="dropdown-item" href="{% url 'books:recommendation' %}">Recommendations</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:news_events' %}">News & Events</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:about' %}">About</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:contact' %}">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#faq" data-toggle="modal" data-target="#faq">FAQ</a>
        </li>
      </ul>

      <form class="form-inline d-flex" action="{% url 'searchs:query' %}" method="GET">
        <input class="form-control" type="text" name="q" value="{{ request.GET.q }}" placeholder="Search ..." required/>
        <button class="btn btn-outline-secondary" type="submit">Search</button>
      </form>

      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link bg-light" href="{% url 'books:user_booklist' %}">My BookList</a>
        </li>
        <li class="nav-item dropdown">
          <a class="btn btn-sm btn-light dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{{ user.image.url }}" alt="" width="35px" style="max-height: 35px;">
            {{ request.user.get_full_name|truncatechars:7 }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'accounts:user_profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'books:user_booklist' %}">My BookList</a>
            <div class="text-muted text-center bg-light">Settings</div>
            <a class="dropdown-item" href="{% url 'accounts:update_account' %}">Settings</a>
            <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change password</a>
            <p class="text-muted text-center bg-light">Book</p>
            <a href="{% url 'books:create' %}" class="btn btn-primary ml-4">&#43; Create book</a>
            <hr/>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
          </div>
        </li>
        {% else %}
        <div class="d-flex justify-content-center align-items-center">
            <a class="btn btn-light mr-2" href="{% url 'accounts:login' %}">Login</a>
            <a class="btn btn-primary" href="{% url 'accounts:create_account' %}">&plus; Join now</a>
        </div>
        {% endif %}
      </ul>

    </div>
</nav>

<div class="modal fade" id="faq" tabindex="-1" role="dialog" aria-labelledby="faqLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="faqLabel">FAQ (Frequently asked questions)</h5> 
        <button data-dismiss="modal" aria-label="Close">&times;</button>
      </div>
      <div class="modal-body">
        <span><h6 class="alert alert-info">APPUS announce you a highly rated book every month</h6></span><br>
        <b>What is APPUS Books</b>
        <ul>
          <li class="lead">
            APPUS Books is a Platform that allows you to connect with other like
            minded readers, swap books, discuss, comment and review books.
          </li>
        </ul>
        <span><b>How APPUS works</b> (step by step)</span>
        <ul>
          <li>Create free account</li>
          <li>Add your book if you have</li>
          <li>Add books to your booklist</li>
          <li>Rate books you like</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<script>
    // When the user scrolls the page, execute myFunction
    window.onscroll = function() {myFunction()};

    // Get the navbar
    var navbar = document.getElementById("navbar");
    var navbarBrand = document.getElementById("navbar-brand-wrapper");

    // Get the offset position of the navbar
    var sticky = navbar.offsetTop;

    // Add the sticky class to the navbar when you reach its scroll position. Remove "sticky" when you leave the scroll position
    function myFunction() {
    if (window.pageYOffset >= 50) {
        navbar.style.background = "#fff";
        navbarBrand.style.padding = "10px";
        navbarBrand.childNodes[3].style.display = 'none';
        navbar.classList.add("shadow-bottom");
    } else {
        navbar.style.background = "#ffffffb3";
        navbarBrand.style.padding = "20px";
        navbarBrand.childNodes[3].style.display = 'block';
        navbar.classList.remove("shadow-bottom");
    }
    }
    
    // FAQ
    // Get the modal
    var modal = document.getElementById('id01');

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>